# Generated by Django 4.0.6 on 2022-07-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Bog`lanish',
                'verbose_name_plural': 'Bog`lanishlar',
            },
        ),
    ]
